### ISSUE TITLE
importing subdistrict csv error

### ISSUE THREAD

**Issue by rashivkp** [itschool/kalolsavam-district#10]
There must be some duplicates in admission number

![import_database_error](https://f.cloud.github.com/assets/2818680/1780311/1bcde9d0-686e-11e3-9766-1c5e8bd8104e.png)

**Comment by rashivkp** [comment]
fixed csv with removing the row, which is a duplicate of a participant_details. but exporting/importing error still exists there..

**Comment by dhayalramk** [comment]
Is this still open? shall i try to solve it?

**Comment by rashivkp** [comment]
@dhayalramk currently, development of this application is not done here as per my knowledge and it was an issue reported 5 year back :smile:
